### ISSUE TITLE
https://blog.stackmob.com/2013/03/newman/ is not available

### ISSUE THREAD

**Issue by kostrse** [stackmob/newman#128]
Unable reach your blog post:
https://blog.stackmob.com/2013/03/newman/

Could you please post the article here on GitHub, as wiki page for example?

**Comment by indykish** [comment]
@kostrse  stackmob guys have moved out. but here is the presentation on scaliak in youtube https://www.youtube.com/watch?v=S_l95GIDCM0

**Comment by kostrse** [comment]
Very sad, wanted to show the article to my colleagues.
Thanks for the link to video.

**Comment by mbarretta** [comment]
@kostrse found something likely similar here: https://www.paypal-engineering.com/2014/02/13/hello-newman-a-rest-client-for-scala/

**Comment by arschles** [comment]
Yep we moved it over
